### PR TITLE
Update to new Documenter change

### PR DESCRIPTION
**Pull request by schillic**
See the breaking change [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/CHANGELOG.md#version-v0240).

### CODE REVIEW

**Comment by mforets** [comment]
should we also bump the Documente dependency?

**Comment by schillic** [comment]
> should we also bump the Documente dependency?

I do not think so. If I understand correctly, it was just a cross-link that was dropped and the URL was already valid before.

**Comment by mforets** [comment]
The question is: if i build LazySets Documentation with v < 0.24.0, does everything work after this PR? I have not tried in my machine, but i can.

**Comment by mforets** [comment]
Actually i haven't built the Docs with the new v0.24 at all. Unfortunately there is no way to preview the built docs online (but i recall seeing some code to do this in another package, but now i forgot).

**Comment by schillic** [comment]
I only changed the links to the final documentation. The building of the documentation is not affected by this PR. It is possible that the links are invalid in some old release of `Documenter`.
If you feel better, we can require the newest version of `Documenter`, but usually it is used automatically anyway.

**Pull request merged**
