### PR TITLE
[WIP #191] HPolygon/HPolytope conversion

### LINKED ISSUE #191: HPolygon and HPolytope
It would be convenient to have a `HPolytope` constructor from a `HPolygon` (and conversely). Also, note that the their fields are `constraints_list` and `constraints` respectively; we should decide for one of these names..

### PR DESCRIPTION
**Pull request by schillic**
Closes #191.

### CODE REVIEW

**Comment by schillic** [comment]
@mforets: I went for a `convert` strategy. If you agree with this solution, I will add the documentation and also move the recent `Zonotope` to the new file.

**Comment by mforets** [comment]
yes, i agree with overloading `convert`, as long as these conversions are straightforward and exact. if there are other complications or overapproximations i would put them on the target set's file (or in the Approximations module, e.g. overloading`overapproximate`)

**Comment by schillic** [comment]
Where should we put the documentation? Create a new section `conversion.md`?

**Comment by mforets** [comment]
ok, looks good!

**Pull request merged**
