### PR TITLE
#139 - Intersection of two sets

### LINKED ISSUE #139: Intersection of two sets
Add a lazy binary operator type `Intersection` (and maybe an n-ary variant) representing the intersection of two sets `S1` and `S2`.
Also have a convenience alias `∩(S1, S2)`, for which Julia's built-in alias is `intersect`.

Related but simpler: #67

### PR DESCRIPTION
**Pull request by schillic**
Closes #139.

Missing:
- [x] support vector (+docs for zero vector case) // we do not implement the support vector for the moment
- [x] include file
- [x] docs
- [x] tests

### CODE REVIEW

**Comment by mforets** [comment]
have you considered to run `is_intersection_empty` in the constructor? (it could be an option). thus if the intersection is empty you return the empty set, otherwise keep the symbolic intersection.

**Comment by schillic** [comment]
This function is not implemented for most types, so this will usually break.

**Comment by mforets** [comment]
my point was that we can remove the `intersection` field, since it really gets info from `is_intersection_empty`, so it's really the same missing functionality (yet). unless the user knows in advance if the intersection is empty or not, and wants to put this info in the type, but maybe that's not the common use case.

**Comment by schillic** [comment]
Okay, the motivation was that this is stored for future queries, but we don't store things for other lazy types, so we can also just remove it.

**Pull request merged**
