### PR TITLE
#83 - VPolygon 1 and 2 vertices corner cases

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by schillic** [comment]
Just to say, #83 was not concerned with the convex hull.

**Comment by mforets** [comment]
does this fix #83 ? if not do you have a breaking example? that we can add here?

**Comment by schillic** [comment]
```julia
∈([1.,2.], VPolygon([[1.,2.]]))
```

**Comment by mforets** [comment]
why is this wrong?

```
julia> ∈([1.,2.], VPolygon([[1.,2.]]))
true
```

**Comment by schillic** [comment]
Ha, it's fixed. I don't understand why, but 👍

**Comment by mforets** [comment]
the `VPolygon` constructor, through convex_hull, was buggy (returning a 0-element set in these corner cases)

**Pull request merged**
