### PR TITLE
Fix bug in check_method_implementation

### LINKED ISSUE #168: Implement vertices_list for HPolytope
We have `HPolytope <: AbstractPolytope`, but this interface requires an implementation of `vertices_list`. Consequently, some operations break.

There is a bug in the interface checking function, hence we did not detect that this function is missing.

Actually, if we have `vertices_list`, we might as well add `VPolytope` because we get `tovrep` for free (we can leave `tohrep` open for now).

### PR DESCRIPTION
**Pull request by schillic**
* [x] fix bug in `check_method_implementation`
* [x] implement `vertices_list` for `HPolytope` >> see #189

### CODE REVIEW

**Comment by schillic** [comment]
@mforets: How should we implement `vertices_list`?
One idea: Implement the intersection for two `Hyperplane`s (result: a `Hyperplane` of lower dimension). Then intersect all defining hyperplanes of the polytope as long as possible until you arrive at 1D. Is this necessary for every (unordered) pair of constraints?

**Comment by mforets** [comment]
does the vertices list functionality depend on  the "check_method_implementation"? how does that work?

**Comment by schillic** [comment]
It just checks if the method exists. When #189 is merged, it should work (we should still try).

**Comment by mforets** [comment]
do you refer to this test?

```julia
@test check_method_implementation(AbstractPolytope, vertices_list,
                                  Function[S -> (S{Float64},)])
```

**Comment by schillic** [comment]
Yes. I just rebased with master. If it gets green, you can merge.

**Comment by mforets** [comment]
the access of the method `vertices_list` requires Polyhedra (it's hidden under a `@require` macro, since we don't want it to be loaded at startup). Maybe we needs `using Polyhedra` before the test of this file?

**Comment by schillic** [comment]
Indeed:
```julia
julia> method_exists(vertices_list, (HPolytope{Float64},))
false

julia> using Polyhedra

julia> method_exists(vertices_list, (HPolytope{Float64},))
true
```

**Comment by schillic** [comment]
Unfortunately, when adding `using Polyhedra`, I get an error with `Halfspace`, see #194.

**Comment by schillic** [comment]
For now my fix is to load this test set last. We should still investigate #194 another time.

**Pull request merged**
