### PR TITLE
#385 `vertices` and `vertices_list`

### LINKED ISSUE #385: `vertices` and `vertices_list`
I see some sort of asymmetry between `VPolygon`'s `vertices_list` field and `VPolytope`  `vertices` field, compared to `HPolygon` and `HPolytope` fields's `constraints`.  Note that we have methods `constraints_list` and `vertices_list`.

Proposal: change `VPolygon`'s field to `vertices`.

### PR DESCRIPTION
**Pull request by schillic**
Closes #385.

### CODE REVIEW

**Comment by schillic** [comment]
I do not understand why the 0.6 build does not work.
```julia
LazySets.Interval: Test Failed
  Expression: σ([1.0], m) == [1.5]
   Evaluated: [1.5] == [1.5]
```
Looks fine to me...

**Comment by mforets** [comment]
Tests pass and docs build in my machine.

**Comment by mforets** [comment]
stupid me, i wanted to push in the other branch..

**Comment by schillic** [comment]
> stupid me, i wanted to push in the other branch..

Can you try out in a clean branch? Then, if it works, we should rebase.

**Comment by mforets** [comment]
> Can you try out in a clean branch?

I wonder if it works with https://github.com/JuliaReach/LazySets.jl/pull/387

**Comment by schillic** [comment]
I removed the commit again.

**Pull request merged**
