### PR TITLE
Clean-up .travis.yml

### PR DESCRIPTION
**Pull request by schillic**
We added two packages that are already in our REQUIRE list, so they are already installed.

### CODE REVIEW

**Comment by mforets** [comment]
about adding GR there, i remember something like it was needed to render the plots in the automatically generated docs using GR (otherwise it was using other default). if you want we can try and see if anything changed.

**Comment by schillic** [comment]
I guess we did not have it in REQUIRE at that time. Because what would `Pkg.add("GR")` do in addition to trying to install it again now? It is executed on the same machine.

**Comment by mforets** [comment]
yeah, i don't know, let's try

**Comment by schillic** [comment]
Where do you see this? The `gh-pages` branch has not been updated since several weeks (probably due to #402).

**Comment by mforets** [comment]
ah, i was looking at the plots. how about if we write `Pkg.pin("Documenter", "0.18.0")` in `.travis.yml`?

**Comment by schillic** [comment]
See #439.

**Pull request merged**
