### PR TITLE
Accept kwargs in 'project' and pass to 'linear_map'

### PR DESCRIPTION
**Pull request by schillic**
Closes #2301 (I copied the idea from there and extended it to the current code base).

### CODE REVIEW

**Comment by mforets** [comment]
not sure about the approach of passing `kwargs...` to a function that actually ignores them. i think that smells like a design problem.

**Comment by mforets** [comment]
here are two other approaches (which are not necessarily orthogonal):

- restrict the scope of `project` by simplifying the API and adding new functions with specialized use cases, eg. `project_template`, ..

- dispatch on "projection algorithms", that is `ConcreteProjection`, `TemplateProjection`, and such.

**Comment by mforets** [comment]
in fact can we do:

```julia
function project(X::LazySet, block::AbstractVector{Int}; kwargs...)
    _project(X, block; kwargs...)
end

# we don't pass kwargs.. to the actual implementation
function _project(B::Ball1, block::AbstractVector{Int})
    return Ball1(B.center[block], B.radius)
end
```

**Comment by schillic** [comment]
No, you cannot do that. If you pass kwargs, then dispatch will search for a method that takes them.

**Comment by mforets** [comment]
ok. then i would suggest to merge this branch, because it adds a new feature (passing backends to the concrete projection), and review again when we have time.

>  i think that smells like a design problem.

one reason is that passing `kwargs...` is against clarity: not sure why/what does the function actually process by looking at the signature..

**Review by mforets — APPROVED** [review]

**Comment by mforets** [comment]
of course there are cases in which passing `kwargs...` is extremely useful, but i'd expect that those are general/API functions and in most cases we pass a fixed number of args

**Comment by schillic** [comment]
The intention of this PR was to close the other PR that started this work. I agree with you that it seems strange to pass kwargs everywhere. But I think you need to do this if you want full control (or set some global variables).

> review again when we have time

Can you open an issue, please? I am not sure what to write there.

**Pull request merged**
