### PR TITLE
remove julia v1.0 from travis build

### PR DESCRIPTION
**Pull request by mforets**
This change removes the travis CI build on julia v1.0, keeping tests on julia v1.5 both on appveyor and on travis.

### CODE REVIEW

**Comment by mforets** [comment]
@schillic i think we should go ahead with this change, and we can always have a branch `v1.0` where we can backport specific update or bug fixes.

**Comment by mforets** [comment]
to do when https://github.com/JuliaReach/LazySets.jl/pull/2618 is ready but add julia v1.2 and test it

**Comment by mforets** [comment]
> [961ee093] + ModelingToolkit v0.8.0

the version that was intalled by CI is too old

**Review by schillic — APPROVED** [review]

**Comment by schillic** [comment]
@mforets If you are okay with my changes, I will apply the necessary changes to #2615 after merging here.

**Comment by mforets** [comment]
the changes lgtm  👍

**Pull request merged**
