### PR TITLE
WIP- Add Julia v1.6 to tests

### PR DESCRIPTION
**Pull request by mforets**
this is to begin testing with the new julia version (no need that we merge this immediately)

### CODE REVIEW

**Comment by schillic** [comment]
I would be surprised if this worked, see #2310 ...

**Comment by mforets** [comment]
i thought that doctests are not ran for all versions, only for v1.4

**Comment by mforets** [comment]
i think we should just skip v1.5 :smile: and prepare everything for v1.6

**Comment by schillic** [comment]
> i thought that doctests are not ran for all versions, only for v1.4

I think that is not the case :wink:
When I run tests locally in v1.5, they always fail in the end in the doctests.

**Comment by mforets** [comment]
indeed, we have set it to behave like that :) https://github.com/JuliaReach/LazySets.jl/blob/master/test/runtests.jl#L29

**Comment by mforets** [comment]
so i take back that "i think we should just skip v1.5 " -- but we will have to remove v1.4 and keep v1.5 (and do the same for the 1.5 to 1.6 transition), because the default printing of some types change between the different versions

**Comment by schillic** [comment]
I am fine with not adapting the doctests to v1.5 and directly going to v1.6. We should only go this two-step way if the changes are incremental. The library itself runs fine in v1.5.

**Comment by mforets** [comment]
it may take some time for the rest of the ecosystem to adapt (to the new Julia version), so i guess that addressing https://github.com/JuliaReach/LazySets.jl/issues/2310 is worthwhile, even if in a couple of weeks we may have to make some work again

**Pull request closed without merging**
