### PR TITLE
#1845 - Make polynomial zonotope subtype lazyset

### LINKED ISSUE #1845: Make PolynomialZonotope a LazySet

### PR DESCRIPTION
**Pull request by mforets**
Closes #1845.

### CODE REVIEW

**Comment by mforets** [comment]
Sorry, can you elaborate on "until we replaced all code parts with the isconvextype trait" ?

**Comment by schillic** [comment]
Algorithms that rely on their argument(s) being convex should dispatch on `isconvextype` instead. For instance, epsilon-close overapproximation of a polynomial zonotope would be incorrect (i.e., not actually epsilon-close).

**Comment by mforets** [comment]
Yes, sure, but that should better be done incrementally, in separate PRs. Think about the `master` branch as the in-development branch. Updating polynomial zonotopes is of independent interest, as in the other cases.

Moreover, note that docstrings already say ".. polygonal approximation of a convex set.". And `isconvextype` of the polynomial zonotope is false. So, it is arguable that something should be done at all. I think it is a good idea to use dispatch in some cases, but in the end, it is a misuse of the function.

**Comment by schillic** [comment]
> Yes, sure, but that should better be done incrementally, in separate PRs.

Agreed, but it should be done in the right order. Breaking things first is not the right order for me.

**Comment by mforets** [comment]
Ok, i think we agree. My point is that this issue *can* be merged independently of making issues that use `isconvextype` because *it doesn't break anything*. There are no tests that will be broken. Calling a function with a non-convex set, while the function needs a convex set, is ultimately a misuse of the function. It will always happen that you can break things. Here we want to use dispatch to not allow such behaviors, which is fine, but it doesn't mean things are broken.

**Comment by mforets** [comment]
> Here we want to use dispatch to not allow such behaviors,

And more interestingly, to selectively apply algorithms based on the property.

**Comment by mforets** [comment]
There are no actionable changes to this PR. It is now blocked by https://github.com/JuliaReach/LazySets.jl/issues/1856 and by https://github.com/JuliaReach/LazySets.jl/issues/1855.

**Comment by mforets** [comment]
Closing as stale; we can merge this and the related PRs in one go..

**Pull request closed without merging**
