### PR TITLE
improve line_search algorithm

### PR DESCRIPTION
**Pull request by schillic**
See #776.

### CODE REVIEW

**Comment by schillic** [comment]
|feature|performance|works (i.e., correctly implemented)?|
|---|---|---|
|`master`|`0.032610 seconds (185.67 k allocations: 15.251 MiB)`|-|
|depth = 1|`0.031774 seconds (186.05 k allocations: 15.268 MiB)`|no|
|check intersection only 1x|`0.035874 seconds (180.95 k allocations: 14.917 MiB)`|no|
|upper/lower bound|`0.020309 seconds (108.77 k allocations: 8.682 MiB)`|yes|
|all (this branch)|`0.017837 seconds (109.05 k allocations: 8.695 MiB)`|no|

**Comment by schillic** [comment]
I decided to end this mess with passing `upper_bound` around. Now we have `ρ_upper_bound` for all relevant lazy operations. For all other set types we use the default `ρ`. The only remainder is `Intersection`, which we can rectify in another PR.
However, with the current settings we cannot run the bouncing ball model anymore...

**Comment by schillic** [comment]
This global variable stuff does not work. We would need to do a heavy refactoring such that the depth is passed through all `ρ` functions correctly.

**Comment by mforets** [comment]
i seriously  consider removing `upper_bound` altogether and defining the overapprox `ρ` for the intersection (there is no such efficient and exact `ρ` for this operation anyways).

**Pull request closed without merging**
