### PR TITLE
Clean-up Documenter configs

### PR DESCRIPTION
**Pull request by schillic**
- do not pin Documenter to old version anymore
- deactivate 'pretty URLs' in local builds to fix links

### CODE REVIEW

**Comment by mforets** [comment]
Note: to be able to make the tests locally again with this PR one has to free Documenter and upgrad it. There are also some new warnings.

```julia
(v1.1) pkg> free Documenter
  Updating `~/.julia/environments/v1.1/Project.toml`
  [e30172f5] ~ Documenter v0.19.7 ⚲⇒ v0.19.7
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [e30172f5] ~ Documenter v0.19.7 ⚲⇒ v0.19.7

(v1.1) pkg> up Documenter
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Documenter ─ v0.22.4
  Updating `~/.julia/environments/v1.1/Project.toml`
  [e30172f5] ↑ Documenter v0.19.7 ⇒ v0.22.4
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [e30172f5] ↑ Documenter v0.19.7 ⇒ v0.22.4


$ juliarc --color=yes docs/make.jl
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: ExpandTemplates: expanding markdown templates.
┌ Warning: no docs found for 'σ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}' in `@docs` block in src/lib/operations.md:245-25
4
│ ```@docs
│ ExponentialMap
│ dim(::ExponentialMap)
│ ρ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ σ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ ∈(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ isbounded(::ExponentialMap)
│ isempty(::ExponentialMap)
│ vertices_list(::ExponentialMap{N}) where {N<:Real}
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/msPrq/src/Expanders.jl:322
┌ Warning: no docs found for '∈(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}' in `@docs` block in src/lib/operations.md:245-25
4
│ ```@docs
│ ExponentialMap
│ dim(::ExponentialMap)
│ ρ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ σ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ ∈(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ isbounded(::ExponentialMap)
│ isempty(::ExponentialMap)
│ vertices_list(::ExponentialMap{N}) where {N<:Real}
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/msPrq/src/Expanders.jl:322
┌ Warning: no docs found for 'vertices_list(::ExponentialMap{N}) where {N<:Real}' in `@docs` block in src/lib/operations.md:245-254
│ ```@docs
│ ExponentialMap
│ dim(::ExponentialMap)
│ ρ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ σ(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ ∈(::AbstractVector{N}, ::ExponentialMap{N}) where {N<:Real}
│ isbounded(::ExponentialMap)
│ isempty(::ExponentialMap)
│ vertices_list(::ExponentialMap{N}) where {N<:Real}
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/msPrq/src/Expanders.jl:322
┌ Warning: no docs found for 'σ(::AbstractVector{N}, ::ExponentialProjectionMap{N}) where {N<:Real}' in `@docs` block in src/lib/operations
.md:261-267
│ ```@docs
│ ExponentialProjectionMap
│ dim(::ExponentialProjectionMap)
│ σ(::AbstractVector{N}, ::ExponentialProjectionMap{N}) where {N<:Real}
│ isbounded(::ExponentialProjectionMap)
│ isempty(::ExponentialProjectionMap)
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/msPrq/src/Expanders.jl:322
┌ Warning: undefined binding 'LazySets.get_row' in `@docs` block in src/lib/operations.md:274-278
│ ```@docs
│ SparseMatrixExp
│ *(::SparseMatrixExp{N}, ::LazySet{N}) where {N<:Real}
│ get_row(::SparseMatrixExp, ::Int)
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/msPrq/src/Expanders.jl:286
```

**Comment by schillic** [comment]
These warnings are old and unrelated to this PR, see #1326.

**Comment by mforets** [comment]
Ok 👍  they are new to me since they showed up only after i upgraded Documenter 😄  ok, loading `Expokit` in the docs should do the trick (i thought we did this already...)

**Comment by schillic** [comment]
Read the issue. We do not do this on purpose. We have to test if occasional output solves the problem.

**Pull request merged**
