### PR TITLE
Add v1.0 build for Travis

### PR DESCRIPTION
**Pull request by schillic**

### CODE REVIEW

**Comment by mforets** [comment]
for now i think we should add it to admitted failures in 1.0. 

because we haven't yet completely transitioned to 1.0 (eg. the interaction with Polyhedra, i had some issues building docs.)

**Comment by schillic** [comment]
But if it works?

**Comment by mforets** [comment]
i haven't transitioned yet to a development workflow in 1.0, because some packages that i use and that we use for in LazySets (or Reachability) haven't transitioned.

**Comment by schillic** [comment]
But you do not have to change anything. Travis runs the build for us.

**Pull request merged**
