### PR TITLE
#541 - Add Project.toml file for v0.7

### LINKED ISSUE #541: Add Project.toml file for v0.7
This file is used to automatically install the dependencies in Julia v0.7. We probably need this to tell Travis which packages to install.
See [the documentation](https://docs.julialang.org/en/latest/stdlib/Pkg/) for more details.

### PR DESCRIPTION
**Pull request by schillic**
Closes #541.

We should first merge #519 and #540 and then rebase (EDIT: done). Then we can locally try out in a fresh environment and test whether Travis accepts this file.

### CODE REVIEW

**Comment by mforets** [comment]
good! should we merge with https://github.com/JuliaReach/LazySets.jl/pull/535 for an environment which actually tests 0.7?

**Comment by schillic** [comment]
Okay, should I add your changes here or the other way around?
Note that the v0.7 build currently fails (you can check the Travis logs).

**Comment by mforets** [comment]
you can merge here

ill have a look at 0.7 build

**Comment by schillic** [comment]
Done, let us see what happens. I added the v0.7 build to the allowed failures for now.

**Pull request merged**
