### PR TITLE
#402 - Use old version of Documenter for Travis build

### LINKED ISSUE #402: Documenter crashes when building the docs
(not related to #400)
```julia
ERROR: LoadError: MethodError: no method matching convert(::Type{AssertionError}, ::String)
Closest candidates are:
  convert(::Type{Any}, ::ANY) at essentials.jl:28
  convert(::Type{T}, ::T) where T at essentials.jl:29
Stacktrace:
 [1] AssertionError(::String) at ./coreimg.jl:14
 [2] walk(::Function, ::Dict{Symbol,Any}, ::Array{Any,1}) at .../.julia/v0.6/Documenter/src/Documents.jl:460
 ...
```

EDIT: The error can be reproduced as follows:
* Remove every file from the folder `docs/src`.
* In `docs/make.jl` remove every line of `pages = [ ... ]`.
* Add the file `docs/src/index.md` with the following content:
````julia
[here](there)

```@example
using Plots
```
````
* Remove every file from the `src` folder (source code) and add `LazySets.jl` with this content:
```julia
module LazySets
import IntervalArithmetic
end
```
* Run `julia docs/make.jl`.

Conclusion: The error is unrelated to us and seems to occur with the combination of hyperlinks and `@example` blocks with `Plots` and `IntervalArithmetic`...

### PR DESCRIPTION
**Pull request by schillic**
Closes #402.

### CODE REVIEW

**Comment by schillic** [comment]
To explain, I wanted to avoid a `Pkg.add("Documenter"); Pkg.pin("Documenter", v"0.18.0")`.
`Pkg.add("Documenter", v"0.18.0")` did not work for some reason, but with two arguments it worked. However, the `v"0.19.0"` is a version that already causes the crash. It just so happens that, at least for me, `Pkg` uses the first version.

**Comment by mforets** [comment]
Great. This is a temporary workaround until the bug is solved in the dependent packages.

**Comment by schillic** [comment]
Do you agree that this closes #402?

**Comment by mforets** [comment]
Yes and no. I agree to close it, although i suggest to have a new issue that highlights the fact that we cannot build docs with v0.19.

**Pull request merged**
