### PR TITLE
#2004 - Generalize vertices type in VPolytope

### LINKED ISSUE #2004: Generalize vertices type in VPolytope
It should be:

```julia
struct VPolytope{N, VT<:AbstractVector{N}} <: AbstractPolytope{N}
    vertices::Vector{VT}
end
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #2004.

### CODE REVIEW

**Comment by mforets** [comment]
tests pass locally. i opened some related-follow up PRs (#2009, #2010, #2011).

**Comment by mforets** [comment]
Bump :trumpet:

**Comment by schillic** [comment]
I already commented in #2004 that the container should also be parameterized.

**Comment by mforets** [comment]
oh boy, i think we are good like this. generalizing for generalizing is not good.

**Comment by mforets** [comment]
Thanks for the review!

> I will add the type parameter for the container in a follow-up PR.

As i said there, i think that the outer vector is the correct level of abstraction. For a specific case, a new set type may be better. Or we can reconsider generalizing the outer type, but for now, i think we can leave this as is..

**Pull request merged**
