### PR TITLE
#93 - Document interfaces

### PR DESCRIPTION
**Pull request by schillic**
See #93.

### CODE REVIEW

**Comment by mforets** [comment]
looks good to me! i updated the DocTestSetup in the new `interfaces.md` file such that there are no doctests issues and added some minor tweaks.

**Comment by mforets** [comment]
ready to be merged when there is the green light..

**Comment by schillic** [comment]
> i updated the DocTestSetup in the new interfaces.md file such that there are no doctests issues

I had not included that because there are no doctests in this file, but okay 😃

**Comment by mforets** [comment]
those `jldoctest` macros included in this file such as the one in `AbstractSingleton` type definition were breaking.

**Comment by schillic** [comment]
Oh, thanks for noticing.

**Pull request merged**
