### PR TITLE
#1599 - Better concrete Minkowski sum of 2D polytopes

### LINKED ISSUE #1599: Generic concrete minkowski sum
By generics i mean function that dispatch on `LazySet`s. We can check if the argument is 2D then use the concrete minkowski sum in v-representation. It is more efficient than using the higher-dimensional approach (see #1597).

### PR DESCRIPTION
**Pull request by schillic**
Closes #1599.

There is a Julia error (unreachable reached). I tried many things.

### CODE REVIEW

**Review by mforets — APPROVED** [review]
I didn't debug the CI error yet.

**Comment by mforets** [comment]
we should debug this or report in case it is a Julia issue (there were similar reports in previous Julia versions). i'll take a look.. if that turns out to be the case, we can mark the failing test(s) as a known error with the `@test_broken` macro.

**Comment by mforets** [comment]
i just ran this on Julia v1.6.0 and i get the following error:

```julia
LazySets.Ballp |   40     40
  1.010276 seconds (1.13 M allocations: 65.852 MiB, 98.69% compilation time)
LazySets.BallInf: Test Failed at /home/mforets/.julia/dev/LazySets/test/Sets/BallInf.jl:205
  Expression: p isa HPolytope{N} && ispermutation(constraints_list(p), [HalfSpace(N[0, -1], N(-2)), HalfSpace(N[0, 1], N(6)), HalfSpace(N[-1, 0], N(0)), HalfSpace(N[1, 0], N(6))])
Stacktrace:
 [1] top-level scope
   @ ~/.julia/dev/LazySets/test/Sets/BallInf.jl:205
 [2] include
   @ ./client.jl:444 [inlined]
 [3] macro expansion
   @ ~/.julia/dev/LazySets/test/runtests.jl:95 [inlined]
 [4] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] macro expansion
   @ ~/.julia/dev/LazySets/test/runtests.jl:95 [inlined]
 [6] macro expansion
   @ ./timing.jl:210 [inlined]
 [7] top-level scope
   @ ~/.julia/dev/LazySets/test/runtests.jl:95
Test Summary:    | Pass  Fail  Total
LazySets.BallInf |  185     1    186
ERROR: LoadError: Some tests did not pass: 185 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/mforets/.julia/dev/LazySets/test/runtests.jl:68
```

**Comment by schillic** [comment]
I still get this:
```julia
julia> Z = minkowski_sum(X + Y, Singleton(zeros(N, 2)))
Unreachable reached at 0x7f2284f31209

signal (4): Illegal instruction
in expression starting at REPL[11]:1
_minkowski_sum_vpolygon at ~/.julia/dev/LazySets/src/ConcreteOperations/minkowski_sum.jl:347
#minkowski_sum#383 at ~/.julia/dev/LazySets/src/ConcreteOperations/minkowski_sum.jl:54
minkowski_sum at ~/.julia/dev/LazySets/src/ConcreteOperations/minkowski_sum.jl:49
unknown function (ip: 0x7f2284f3184c)
[...]
```

**Review by mforets — APPROVED** [review]

**Pull request merged**
