### PR TITLE
#720 - add upper bounds

### LINKED ISSUE #720: Add ρ upper bound for an intersection
Proposal: add 

```julia
ρ_upper_bound(d, cap::Intersection) = min(ρ_upper_bound(d, cap.X), ρ_upper_bound(d, cap.Y))
```
for intersections.

We can also add a default `ρ_upper_bound` which returns the exact `ρ`.

See #706, #707 for another approach that uses type dispatch.

### PR DESCRIPTION
**Pull request by mforets**
Closes #720.

### CODE REVIEW

**Comment by schillic** [comment]
This is not what you wrote in #720.

**Comment by mforets** [comment]
> This is not what you wrote in #720.

Hmm what do you think about adding it as:

```julia
function ρ_upper_bound(d::AbstractVector{N}, cap::Intersection{N}) where {N<:AbstractFloat}
    return min(ρ_upper_bound(d, cap.X), ρ_upper_bound(d, cap.Y))
end
```

**Comment by schillic** [comment]
Why `AbstractFloat`?

**Comment by mforets** [comment]
i don't know, let's change it to real.

the problem is that i get (here `X` is a HPolygon):

```julia
julia> ρ_upper_bound(rand(2), X ∩ X)
ERROR: MethodError: LazySets.Approximations.ρ_upper_bound(::Array{Float64,1}, ::LazySets.Intersection{Float64,LazySets.HPolygon{Float64},LazySets.HPolygon{Float64}}) is ambiguous. Candid
ates:
  ρ_upper_bound(d::AbstractArray{N,1}, cap::LazySets.Intersection{N,S1,S2} where S2<:LazySets.LazySet{N} where S1<:LazySets.LazySet{N}) where N<:AbstractFloat in LazySets.Approximations
at /Users/forets/.julia/v0.6/LazySets/src/Approximations/upper_bounds.jl:73
  ρ_upper_bound(d::AbstractArray{N,1}, cap::LazySets.Intersection{N,#s105,S} where #s105<:LazySets.LazySet) where {N<:AbstractFloat, S<:LazySets.AbstractPolytope{N<:AbstractFloat}} in La

zySets.Approximations at /Users/forets/.julia/v0.6/LazySets/src/Approximations/upper_bounds.jl:67
Possible fix, define
  ρ_upper_bound(::AbstractArray{N<:AbstractFloat,1}, ::LazySets.Intersection{N<:AbstractFloat,#s105,S<:LazySets.AbstractPolytope{N<:AbstractFloat}} where #s105<:LazySets.LazySet{N<:Abstr
actFloat})
```

**Comment by mforets** [comment]
it is fixed defining

```julia
function ρ_upper_bound(d::AbstractVector{N},
                       cap::Intersection{N, <:LazySet, S}) where {N<:Real, S<:AbstractPolytope{N}}
    return min(ρ_upper_bound(d, cap.X), ρ_upper_bound(d, cap.Y))
end
```

**Comment by schillic** [comment]
You have to add `ρ_upper_bound(d::AbstractVector{N}, cap::Intersection{N, AbstractPolytope{N}, AbstractPolytope{N}}; kwargs...) where {N<:AbstractFloat}`
And actually you should also add the symmetric version where the first element of the `Intersection` is the `AbstractPolytope`.

**Pull request merged**
