### PR TITLE
Update AbstractHyperrectangle support function

### PR DESCRIPTION
**Pull request by mforets**
See [this comment](https://github.com/JuliaReach/LazySets.jl/pull/1785#discussion_r356628746).

### CODE REVIEW

**Comment by schillic** [comment]
I would not merge this.

**Comment by mforets** [comment]
Why? Do you have an example where this is worse than the version in master?

BTW i wonder how does the computation compare to using directly BLAS functions. I'll have a look.,

**Comment by schillic** [comment]
It should be obvious that adding `n` multiplications is generally slower.

**Comment by schillic** [comment]
Huh, I just tried and this version is actually faster. My world falls down.

**Comment by schillic** [comment]
One advantage of the `master` version is for sparse vectors (the loop skips `0` entries in the vector).

```julia
julia> n = 100; H = Hyperrectangle(ones(n), ones(n)); d = zeros(n); d[1] = 1.;

julia> @btime ρ($d, $H);  # master
  96.579 ns (0 allocations: 0 bytes)

julia> @btime ρ($d, $H);  # this branch
  125.644 ns (0 allocations: 0 bytes)
```

**Comment by mforets** [comment]
That's fair enough. In [this notebook](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/sets/Hyperrectangle_supp.ipynb) i added some other benchmarks, that may be useful if we want to review this again in the future.

**Comment by schillic** [comment]
Woops, sorry, I had the wrong numbers in the post [here](https://github.com/JuliaReach/LazySets.jl/pull/1826#issuecomment-564582595). The text was correct. The version here was faster for positive dense vectors.

**Comment by mforets** [comment]
Too late :laughing:  The last figure in [the notebook](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/sets/Hyperrectangle_supp.ipynb) shows that `ρ2b` is the fastest in almost all cases, by a factor between 1 and 1.8 with respect to the function in master, `ρ0`.

**Pull request closed without merging**
