### PR TITLE
Update convex_hulls.md

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by mforets** [comment]
Yes, see the generated webpage in https://juliareach.github.io/LazySets.jl/latest/man/convex_hulls.html#Symbolic-convex-hull-1

**Comment by mforets** [comment]
screen shot 2018-11-23 at 13 34 39

**Comment by schillic** [comment]
There are more warnings in this file. Do you plan to address them? Otherwise we should create an issue.

**Comment by mforets** [comment]
i didn't see there were warnings with `blkdiag` and `full` (or, i thought those would be clear with `using SparseArrays`). let me send the changes in another PR.

**Pull request merged**
