### PR TITLE
[WIP] hybrid zonotope reachability algorithm example

### PR DESCRIPTION
**Pull request by schillic**

### CODE REVIEW

**Comment by mforets** [comment]
stash commits?

**Comment by mforets** [comment]
also we should delete `reach_continuous(A, b, X0, δ, μ, T)` since it is not used here

**Comment by schillic** [comment]
I would keep this branch as a sandbox and just copy the code to separate PRs when they are ready.

**Comment by mforets** [comment]
should we close this PR? (i'm not proposing to delete the branch)

**Pull request closed without merging**
