### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by schillic** [comment]
Are you sure that we can make a patch release when `Project.toml` has been modified?

**Comment by mforets** [comment]
i'm not sure; if automatic merging has that guideline i didn't find it in the docs ([here](https://github.com/JuliaRegistries/General#automatic-merging-of-pull-requests))

**Comment by mforets** [comment]
Ok

**Comment by schillic** [comment]
I did not mean to close, just to wait. I am fine with a release now. But I think it must be a minor release instead now that we extended the upper bounds.

**Pull request closed without merging**
