### PR TITLE
Fix broken unit tests

### LINKED ISSUE #71: Failing doctests should fail the build
@mforets: Currently there is a failing doctest in master:

```julia
> File: .../LazySets/src/Ball1.jl

> Code block:                                                                                                       

\`\`\`jldoctest
julia> σ([0.,1], B)
1-element Array{Float64,1}:
 1.0
 0.0
\`\`\`

> Subexpression:                                                                                                    

    σ([0.,1], B)

> Output Diff:                                                                                                      

1-element 2-element Array{Float64,1}:
 1.0
 0.00.0
 1.0 
```
However, Travis does not complain.
See [here](https://github.com/JuliaDocs/Documenter.jl/issues/527) how to potentially implement this.

### PR DESCRIPTION
**Pull request by schillic**
EDIT: Does *not* close the issue #71.

### CODE REVIEW

**Comment by schillic** [comment]
I vote for activating the other unit tests in the builds. This will take a bit longer, but we will notice when problems are introduced.
`Polyhedra` tests are only available in v0.6 at the moment (that package is also needed for plotting), so I propose the following settings.
```julia
# old, unchanged
global test_suite_basic = true
global test_suite_doctests = VERSION >= v"0.7-" # only run doctests with new Julia version
# new
global test_suite_polyhedra = VERSION < v"0.7-" # only run doctests with old Julia version (for now)
global test_suite_plotting = VERSION < v"0.7-" # only run doctests with old Julia version (for now)
```

**Comment by mforets** [comment]
> I vote for activating the other unit tests in the builds. This will take a bit longer, but we will notice when problems are introduced.

I agree too. Once `Polyhedra` tests pass in 0.7 too we can switch all default tests to `true`.

**Comment by schillic** [comment]
I had to undo the commit for strict doctests because `Optim` has many undocumented functions and for some reason `Documenter` complains about them (although we explicitly say
`modules = Module[LazySets, Approximations]`).

**Comment by mforets** [comment]
Does `strict=true` imply that if we have an undocumented function the build breaks? (If yes, i think that's "too strict".)

**Comment by schillic** [comment]
> Does strict=true imply that if we have an undocumented function the build breaks? (If yes, i think that's "too strict".)

Unfortunately, that is the case (and there is no fine-tuning option ).

**Comment by mforets** [comment]
> Unfortunately, that is the case (and there is no fine-tuning option ).

Alright. Documented [here](https://github.com/JuliaDocs/Documenter.jl/blob/bfa7b6b12581fad302e1521ee82615577646a4a4/src/Documenter.jl#L163), i'd like `strict=true` *but* it doesn't break if `checkdocs` fails. But it seems like if `strict=true` then `checkdocs` option is ignored?

**Comment by mforets** [comment]
i suspect (but i'm not 100% sure) that the failure with the v1.0 is the new restriction of the package manager to refuse installing packages which are known not to work in > 0.7. the error message says

```julia
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CDDLib [3391f64e]:
 CDDLib [3391f64e] log:
 ├─possible versions are: [0.0.1, 0.1.0-0.1.4, 0.2.0-0.2.3, 0.3.0-0.3.2] or uninstalled
 ├─restricted to versions 0.3.2-* by an explicit requirement, leaving only versions 0.3.2
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by mforets** [comment]
finally

screen shot 2018-09-30 at 23 08 06

let's temporarily allow failure in the 1.0 build until the issue with the dependency is fixed.

**Comment by schillic** [comment]
I would rather remove `CDDLib`/`Polyhedra` from the `test/REQUIRE` file because
1. we do not use these packages in the newer versions, and
2. for the v0.6 build we need to write the `Pkg.add` commands explicitly.

**Pull request merged**
