### PR TITLE
#690 - Fix T parameter and remove deprecated imports

### LINKED ISSUE #690: Adapt `HRep{T, N}`
Polyhedra#master the H- (resp V-) representations are not parametrized anymore in the set dimension. We should adapt to this change in the constructors `HPolytope` and `VPolytope`.

### PR DESCRIPTION
**Pull request by mforets**
Closes #690.

### CODE REVIEW

**Comment by mforets** [comment]
It fails in v0.6 because this changeset is for the new version of Polyhedra, which does no longer support v0.6. 

What do we want to do now? Shall we keep this change for later when we drop the support for 0.6 in LazySets? I don't like the idea of keep patching with if-else-version for each new udpate in other packages.

**Comment by schillic** [comment]
Okay for waiting. Maybe add a milestone and add this issue/PR to it.

**Comment by mforets** [comment]
As a quick and momentary fix we can special case this function based on the julia version.

**Comment by mforets** [comment]
i keep getting this issue (unrelated to this PR)

```julia
julia> using LazySets

julia> using Polyhedra
┌ Warning: Package LazySets does not have CDDLib in its dependencies:
│ - If you have LazySets checked out for development and have
│   added CDDLib as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with LazySets
└ Loading CDDLib into LazySets from project dependency, future warnings for LazySets are suppressed.
WARNING: could not import CDDLib.CDDLibrary into LazySets
```

**Pull request merged**
