### PR TITLE
#389 - Change Travis build versions

### LINKED ISSUE #389: Change Travis build versions
Result of a discussion with @mforets:
* We want to have build tests for the following Julia versions: v0.6, v0.6.2, v0.6.4, v0.7 (beta)
* We only want to allow failures for v0.7. Previously the builds randomly broke, but we hope that they are more stable now.

### PR DESCRIPTION
**Pull request by schillic**
Closes #389.

### CODE REVIEW

**Comment by schillic** [comment]
I saw that we send coverage data to `Coveralls` but never retrieve that data. Should we change this or add a badge on the main page?

**Comment by mforets** [comment]
+1 
I think we are fine with `codecov` which already works

**Comment by mforets** [comment]
actually, `- 0.6` installs the same as `- 0.6.4`

**Comment by schillic** [comment]
Ah, this explains why it fell back to v0.6.4. Does `- 0.6.0` work?

**Comment by mforets** [comment]
i didn't try, but i think it would work.

**Comment by schillic** [comment]
Yep, it worked.

**Pull request merged**
