### PR TITLE
ExponentialMap parametric N

### LINKED ISSUE #178: Add numeric type parameter for ExponentialMap
See #132.

### PR DESCRIPTION
**Pull request by mforets**
Closes #178.

### CODE REVIEW

**Comment by mforets** [comment]
notes: 

- i've removed the `<: Real` dependency because this is not really a restriction
- the unit test in different numeric types will be added in #132

**Comment by schillic** [comment]
> i've removed the <: Real dependency because this is not really a restriction

This is a bit inconsistent now. We can also remove them from all other set types again if you want.

**Comment by mforets** [comment]
i removed it from the lazy mexp constructors, since you could want complex (we could use `Number` ?) ,but i'm not proposing to remove it from all other set types.

**Comment by schillic** [comment]
Okay, merge?

**Pull request merged**
