### PR TITLE
#162 #145 #165 - add macro to restore old array type behavior

### LINKED ISSUE #145: Move algebraic definitions from functions to constructors
For `MinkowskiSum` and `CartesianProduct` we have defined neutral/absorbing elements only for the `+`/`*` functions, but not for the constructor. It would be more consistent to define them using new constructors so that `A + B === MinkowskiSum(A, B)` in all cases.

Note that one has to add type parameters to avoid ambiguities. We saw that for `ConvexHull` where we already have this (because there is no separate function symbol).

### LINKED ISSUE #162: Add macros to automatically create boilerplate code
I want to try [metaprogramming in Julia](https://docs.julialang.org/en/stable/manual/metaprogramming/#Code-Generation-1) for repeated patterns that we have such as defining algebraic laws like neutral/absorbing elements for operations. I imagine something like:
```julia
@commutative_monoid(ConvexHull, EmptySet)
@commutative_monoid_absorbing(MinkowskiSum, ZeroSet, EmptySet)
```
These macros are supposed to create the three (resp. six) constructors for the different combinations.
I think this is easier to both read and write, less error-prone, and easier to adapt to changes.

The only downside I see is that we cannot write documentation for such constructors anymore. But we should probably just mention this in the type's documentation anyway.

### LINKED ISSUE #165: Extend CHArray with a CH
In #103 we implemented the convex hull array. One would like that `CH(a, b)` where `a` is a `CHArray` and `b` another lazy set, extends the `.array` field of `a` with the set `b`.

### PR DESCRIPTION
**Pull request by schillic**
Closes #162 and closes #145 and closes #165.

### CODE REVIEW

**Comment by mforets** [comment]
i fail to see what is the logic for these blocks:

```julia
...
        # if the array set type has already been defined, create combinations
        if isdefined(:array_constructor) &&
                method_exists(array_constructor, (Type{$SET},))
            @eval(@array_neutral($(esc(SET)),
                                 $(esc(NEUT)),
                                 array_constructor($(esc(SET)))))
        elseif isdefined(:is_array_constructor) &&
                method_exists(is_array_constructor, (Type{$SET},))
            @eval(@array_neutral($(esc(SET)),
                                 $(esc(NEUT)),
                                 $(esc(SET))))
        end
```

why is there an `if` clause? what is the difference between `array_constructor` and `is_array_constructor`?

**Comment by schillic** [comment]
This is needed so that you can use the macros `@neutral`, `@absorbing` and `@declare_array_version` in any order. The if clauses make sure that the functions are defined only once.

**Comment by mforets** [comment]
> This is needed so that you can use the macros @neutral, @absorbing and @declare_array_version in any order. 

ok

> The if clauses make sure that the functions are defined only once.

i guess my confusion arises from the fact that both `array_constructor` and `is_array_constructor` are defined in the same place (`declare_array_version`). how is that we have two `@eval`'s? isn't it used only the first one? thanks

**Comment by schillic** [comment]
Okay, I admit that it is overengineered :)

We have `@neutral` two times, once for the normal type and once for the array type.
```julia
@neutral(MinkowskiSum, ZeroSet)
@neutral(MinkowskiSumArray, ZeroSet)
```
Those calls to the macro should have a slightly different behavior. I use the two functions to detect which one.

**Pull request merged**
