### PR TITLE
#630 - Concrete intersection between HPolytope and VPolytope

### LINKED ISSUE #630: Concrete intersection between HPolytope and VPolytope
```julia
julia> using LazySets, Polyhedra

julia> P1 = HPolytope(rand(10, 2), rand(10));
julia> P2 = VPolytope([rand(2) for i in 1:10])
julia> intersection(P1, P2)

MethodError: no method matching intersection(::LazySets.HPolytope{Float64}, ::LazySets.VPolytope{Float64})
Closest candidates are:
  intersection(::LazySets.HPolytope{N<:Real}, ::LazySets.HPolytope{N<:Real}; backend, prunefunc) where N<:Real at /Users/forets/.julia/v0.6/LazySets/src/HPolytope.jl:273
  intersection(::LazySets.VPolytope{N<:Real}, ::LazySets.VPolytope{N<:Real}; backend, prunefunc) where N<:Real at /Users/forets/.julia/v0.6/LazySets/src/VPolytope.jl:189

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
 [2] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/forets/.julia/v0.6/IJulia/src/execute_request.jl:193
 [3] (::Compat.#inner#14{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /Users/forets/.julia/v0.6/Compat/src/Compat.jl:332
 [4] eventloop(::ZMQ.Socket) at /Users/forets/.julia/v0.6/IJulia/src/eventloop.jl:8
 [5] (::IJulia.##13#16)() at ./task.jl:335
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #630.

### CODE REVIEW

**Comment by schillic** [comment]
> i was using prunefunc=removehredundancy! by default for the intersection in all cases

Oh, you are right. Then is it okay to merge the four implementations for you?

**Comment by mforets** [comment]
Yes. Since`VP ∩ VP -> VP`, `HP ∩ HP -> HP`, `VP ∩ HP -> HP`, `HP ∩ VP -> HP`, we have to check if both polytopes are in V-rep, otherwise return an H-rep.

**Comment by schillic** [comment]
Okay, then we can just remove the output type and add the following lines at the end:
```julia
if P1 isa VPolytope && P2 isa VPolytope
    T = VPolytope
else
    T = HPolytope
end
return T(Pint)
```

**Comment by schillic** [comment]
Another possibility is to give the user the choice of the output type `T`, with the default value as we define it currently.

**Comment by schillic** [comment]
> Merging #633 into master will increase coverage by 6.47%. :tada:

**Pull request merged**
