### PR TITLE
#1579 - Add subfolders in directory

### LINKED ISSUE #1579: Add subfolders in directory
`LazySets/src` has 74 files. This issue is to consider splitting into some subfolders with clear descriptive names, and: (i) not too many subfolders otherwise it turns the problem around (where is that file?) and (ii) preferably that they are just one-word descriptive names.

Here is a proposal:

```julia
|- Approximations
|
|- Arrays
|
|- ConcreteOperations
|   |- minkowski_sum.jl . . .
|
|- Initialization
|   |- init_CDDLib.jl . . .
|
|- Interfaces
|   |- AbstractHyperrectangle.jl . . .
|   |- aliases.jl
|
|- LazyOperations
|   |- MinkiwskiSum.jl . . .
|
|- Parallel
|
|- Plotting
|   |- mesh.jl . . .
|
|- Sets
|   |- Ball1.jl . . .
|
|- Utils
|   |- helper_functions.jl
|    
|- LazySets.jl
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #1579.

The only file not captured is `convert.jl`. ~Where should we put this?~

~I also split the `HPolyhedron.jl` file into two, one now being `HPoly.jl` with all the stuff that affects our `HPoly` alias.~

Since this PR breaks most open PRs, I think we should first merge the remaining active PRs (~#1612~, #1628, #1632). Then I can do the conflict resolution here.

### CODE REVIEW

**Comment by mforets** [comment]
> The only file not captured is convert.jl. Where should we put this?

It can go at top-level since it involves all lazysets types.

> Since this PR breaks most open PRs, I think we should first merge the remaining active PRs (#1612, #1628, #1632). Then I can do the conflict resolution here.

Ok. These can take 1-2 weeks though.

**Comment by schillic** [comment]
> Ok. These can take 1-2 weeks though.

No problem. If you want to move on instead, the conflicts will actually be easy to resolve. But I would appreciate if not too many new PRs are opened until this one gets in.

**Comment by schillic** [comment]
I added another commit that splits the `HPolyhedron.jl` file into two, one now being `HPoly.jl` with all the stuff that affects our `HPoly` alias.

**Comment by schillic** [comment]
> Please don't

Okay, I removed it again.

**Pull request merged**
