### PR TITLE
Revise HalfSpace code

### PR DESCRIPTION
**Pull request by schillic**
The first commit also moves some functions in the docs and changes some signatures so they only occur once in the docs.
The second and third commit change the name of two helper functions and change their signatures to avoid extra allocations.

### CODE REVIEW

**Comment by mforets** [comment]
What motivates using `nothing` instead of `default_lp_solver(N)` etc? I find the latter more readable.

**Comment by schillic** [comment]
Oops sorry, I merged the wrong PR ...

> What motivates using nothing instead of default_lp_solver(N) etc? I find the latter more readable.

This was to make the docs catch the right method. It did not work otherwise.

**Comment by schillic** [comment]
Should I undo the merge?

**Comment by mforets** [comment]
> This was to make the docs catch the right method

Ok, that's fine, so it's a workaround for our docs setup.

**Comment by mforets** [comment]
> Should I undo the merge?

No

**Pull request merged**
