### PR TITLE
Revise benchmarks folder

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by schillic** [comment]
I am not convinced that adding random numbers is good for benchmarking unless the `judge` call uses the same objects. Do you know?

**Comment by mforets** [comment]
In the calls to `rand`, the seed `rng` is fixed for each `n`, so the values of `d` and `X` are reproducible.

**Comment by mforets** [comment]
I didn't remove it; it's been renamed them to `SUITE["ρ"]["LinearMap of $(string(set_type))", "dense", n] = @benchmarkable ρ($d, $Y)` in lines 22-23.

In follow-up PR i plan to add other versions of similar tests, such as sparse vectors. Adding other set types is also interesting.

**Comment by schillic** [comment]
Indeed, sorry!

**Pull request merged**
