### PR TITLE
operations on simple sparse polynomial zonotopes

### PR DESCRIPTION
**Pull request by lucaferranti**
This PR adds the operations on SSPZ described in Niklas presentation. Currently I added those into the same file of SSPZ, but maybe we want to move those in the corresponding files in `concrete_operations`?

### TODO

- [x] ~~linear combination~~ in future PR
- [x] ~~quadratic map~~ in future PR
- [x] ~~convex hull~~ in future PR
- [x] tests

### CODE REVIEW

**Comment by lucaferranti** [comment]
> Looks good after moving the binary methods to the respective files 👍

among the functions implemented here, it seems only `cartesian_product` and `minkowski_sum` have a corresponding file in `ConcreteOperations`, should I create a new file for `linear_map` or leave it under `SimpleSparsePolynomialZonotope.jl` ?

**Comment by schillic** [comment]
`linear_map` is not binary and hence we keep it in the same file.

**Comment by lucaferranti** [comment]
moved the files. Out of curiosity, does LazySets rely on promotion mechanisms or how should it handles things like e.g.

```julia
minkowski_sum(::SimpleSparsePolynomialZonotope, ::Star)
```

**Review by schillic — APPROVED** [review]

**Comment by schillic** [comment]
> moved the files. Out of curiosity, does LazySets rely on promotion mechanisms or how should it handles things like e.g.
> 
> ```julia
> minkowski_sum(::SimpleSparsePolynomialZonotope, ::Star)
> ```

That would require adding a specific method and is out of scope for now.

**Comment by lucaferranti** [comment]
btw currently the following fails

```julia
linear_map(I, S)
```
where `S` is SSPZ, the reason for this is that `I` is uniform scaling and it's not a subtype of `AbstractMatrix`, that's arguably a pretty boring linear map to apply. Is it worth to change the signature for that?

**Comment by schillic** [comment]
> Is it worth to change the signature for that?

I do not think so.

**Review by mforets — APPROVED** [review]

**Pull request merged**
