### PR TITLE
#1925 - Refactor boundnedness check for HPolygon

### LINKED ISSUE #1925: Refactor boundnedness check for HPolygon
https://github.com/JuliaReach/LazySets.jl/blob/ffe0320ab37a2cc7e06eaf461f04b8743554c4aa/src/Interfaces/AbstractHPolygon.jl#L575 converts to `HPolyhedron`, but `isbounded_unit_dimensions` can be called directly and this makes `isbounded(::HPolygon, false)` ~15x faster.

### PR DESCRIPTION
**Pull request by mforets**
Closes #1925.

### CODE REVIEW

**Comment by mforets** [comment]
```julia
using Revise, LazySets, BenchmarkTools

P = rand(HPolygon);

@btime isbounded($P, false) # master
  52.567 μs (310 allocations: 20.11 KiB)

@btime LazySets.isbounded_unit_dimensions($P) # master
  3.140 μs (76 allocations: 3.63 KiB)

@btime isbounded($P, false) # this branch
  3.123 μs (76 allocations: 3.63 KiB)
```

**Comment by schillic** [comment]
Apparently the special case of a polygon with no constraints needs to be treated differently:
```julia
LazySets.Polygon: Error During Test at test\unit_Polygon.jl:87
  Test threw exception
  Expression: !(isbounded(HPolygon{N}(), false)) && !(isbounded(HPolygonOpt{N}(), false))
  AssertionError: the polygon has no constraints
```

**Comment by schillic** [comment]
Do you think that this implementation is also more efficient in higher dimensions? Then we should rather change `isbounded(::Vector{LinearConstraint})`.

**Comment by mforets** [comment]
The "gain" in this PR comes from the fact that evaluating the support function of the given `HPolygon` directly is cheaper than converting to a polyhedron and evaluating its support function (using LPs). 

> Then we should rather change isbounded(::Vector{LinearConstraint}).

Where is that function defined?

**Comment by schillic** [comment]
> Where is that function defined?

Sorry, I missed the conversion to `HPolyhedron`.

**Comment by mforets** [comment]
Thanks for the review.

**Pull request merged**
