### PR TITLE
Increase timeout for docs build

### PR DESCRIPTION
**Pull request by schillic**
Recently we breach the 30 minutes :face_with_head_bandage:

### CODE REVIEW

**Review by mforets — APPROVED** [review]

**Comment by schillic** [comment]
> Timeout (40 minutes) reached. Terminating "julia --project=docs/ docs/make.jl"

Wow, something seems to be broken... I'll try to build locally.

**Comment by schillic** [comment]
My findings: The majority of the time is spent in compiling all the methods. Apart from that, the docs build very fast (7 seconds) with two exceptions:
* https://github.com/JuliaReach/LazySets.jl/blob/master/docs/src/man/reach_zonotopes_hybrid.md
    * We compute 4k sets and plot them (~125 seconds).
* https://github.com/JuliaReach/LazySets.jl/blob/master/docs/src/man/lazy_intersections.md
    * Here we use `@btime` several times (I stopped it after ~10 minutes). Is this a regression?

@mforets What do you think about replacing the `@btime` by ``@time` from the docs (only takes 1 second then) and using faster parameters in the reachability algorithm? I tried `δ = 0.01` (10x bigger) and that only takes 2 seconds with almost the same result.

**Comment by schillic** [comment]
I pushed a proposal. Let's look at the build time.

**Comment by mforets** [comment]
> @mforets What do you think about removing the @btime from the docs (only takes 1 second then) and using faster parameters in the reachability algorithm? I tried δ = 0.01 (10x bigger) and that only takes 2 seconds with almost the same result.

sounds good!

> Here we use @btime several times (I stopped it after ~10 minutes). Is this a regression?


idk, i can check too

**Comment by schillic** [comment]
26 minutes :tada:

**Review by mforets — APPROVED** [review]

**Pull request merged**
