### PR TITLE
mixed improvements

### PR DESCRIPTION
**Pull request by schillic**
- added output types to all functions
- turned shorthand function style into `function ... end` blocks (except for constructors)
- renamed `is_contained` -> `∈`
- checked #49
- minor doc fixes

### CODE REVIEW

**Comment by mforets** [comment]
some comments:

- we can have `iscontained` (or `is_contained` ?) as an alias.

- some functions enter in 80 characters => they fit nicely as one-liners.. is there any doc-related reason for the change? just aesthetics?

- the Output block of `sign_cadlag` is wrong, should say: `1 if x≥0, -1 otherwise.` shall we update it here? maybe add too:

```
### Notes

This is the sign function right-continuous at zero (see [cadlag function](https://en.wikipedia.org/wiki/C%C3%A0dl%C3%A0g)). It can be used with vector-valued arguments via the dot operator.
```

**Comment by schillic** [comment]
> we can have iscontained (or is_contained ?) as an alias.

We already have `in`, I think this suffices.

> some functions enter in 80 characters => they fit nicely as one-liners

Citation needed :) I saw one case in `convex_hull_algorithms.jl`.
I prefer to break documentation sentences after the period to avoid moving everyhing around with a later change.

**Comment by schillic** [comment]
> the Output block of sign_cadlag is wrong

I fixed it here.

**Comment by mforets** [comment]
> We already have in, I think this suffices.

ok. it's the same as `Base.\in` ? or `in` should be declared too? i didn't find it in this commit

> Citation needed :)

i don't have one, no problem :)

**Comment by schillic** [comment]
> >  We already have in, I think this suffices.
>
> ok. it's the same as Base.\in ? or in should be declared too? i didn't find it in this commit

Sorry, I should have said that. It seems to work automatically. It just aliases `∈` and then calls the right function.

**Pull request merged**
